version: "3.8"

# mais info: https://youtu.be/tQ6-A1wl-C0
services:
  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes", "--port", "6379"]
    volumes:
      - redis_data:/data
    deploy:
      # mode: replicated
      # replicas: 1
      # resources:
      #   limits:
      #     cpus: "0.2"
      #     memory: 312M
      # placement:
      #   constraints:
      #     - node.role == maanager
    networks:
      - yosoft-network
      
volumes:
  redis_data:
    external: true

networks:
  yosoft-network:
    external: true