version: "3"
services:
  buider:
    tty: true
    stdin_open: true
    image: tooljet/tooljet-ce:latest
    restart: always
    ports:
      - 8002:80
    depends_on:
      - postgres
    environment:
      SERVE_CLIENT: "true"
      PORT: "80"
    command: npm run start:prod
    volumes:
      - ../data/tooljet_data:/var/lib/postgresql/13/main
    networks:
      - yosoft-network
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.builder.rule=Host(`builder.yosoft.app`)"
        - "traefik.http.routers.builder.entrypoints=websecure"
        - "traefik.http.routers.builder.tls.certresolver=myresolver"
        - "traefik.http.services.builder.loadbalancer.server.port=8002" # Siempre debemos definir un puerto.
  
  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

# Uncomment if ENABLE_TOOLJET_DB=true
  # postgrest:
  #   image: postgrest/postgrest:v10.1.1.20221215
  #   restart: always
  #   depends_on:
  #     - postgres
  #   env_file: .env
  #   environment:
  #     - PGRST_SERVER_PORT=80
networks:
  yosoft-network:
    external: true