# docker stack deploy -c registro.yml registro
version: "3.5"

services:
  registry:
    image: registry:2
    volumes:
      - ./registro_data:/var/lib/registry
    networks:
      - yosoft-network
    # secrets:
    #   - registry_htpasswd
    # environment:
    #   REGISTRY_AUTH: htpasswd
    #   REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    #   REGISTRY_AUTH_HTPASSWD_PATH: /run/secrets/registry_htpasswd
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.registro.rule=Host(`registro.yosoft.app`)"
        - "traefik.http.routers.registro.entrypoints=websecure"
        # - "traefik.http.routers.registro.entrypoints=web"
        - "traefik.http.routers.registro.tls.certresolver=myresolver"
        # - "traefik.http.routers.registro.tls=true"
        - "traefik.http.services.registro.loadbalancer.server.port=5000" # Siempre debemos definir un puerto.     

networks:
  yosoft-network:
    external: true

# secrets:
#   registry_htpasswd:
#     external: true
